# Generated by Django 4.2.23 on 2025-09-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('car', 'Car Loan'), ('real_estate', 'Real Estate Loan')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_debt_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cic_group', models.IntegerField(help_text='1..5 (1 = best, 5 = worst)')),
                ('credit_history_months', models.IntegerField(default=0)),
                ('credit_utilization_pct', models.FloatField(blank=True, null=True)),
                ('num_late_payments_24m', models.IntegerField(default=0)),
                ('num_new_inquiries_6m', models.IntegerField(default=0)),
                ('credit_mix_types', models.IntegerField(default=1, help_text='Number of different credit types')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vehicle_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_duration_months', models.IntegerField(default=0)),
                ('salary_payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dti', models.FloatField(blank=True, null=True)),
                ('ltv', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_score', models.FloatField()),
                ('eligible', models.BooleanField()),
                ('knockout_reasons', models.JSONField(blank=True, null=True)),
                ('score_breakdown', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='user_profile.loanapplication')),
            ],
        ),
    ]
