# Generated by Django 4.2.23 on 2025-09-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanevaluation',
            name='ai_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanevaluation',
            name='ai_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanevaluation',
            name='ai_raw_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanevaluation',
            name='ai_recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanevaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
