# Generated by Django 4.2.23 on 2025-09-30 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_loanevaluation_ai_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanevaluation',
            name='ai_breakdown',
        ),
        migrations.RemoveField(
            model_name='loanevaluation',
            name='ai_match_score',
        ),
        migrations.RemoveField(
            model_name='loanevaluation',
            name='ai_raw_response',
        ),
        migrations.RemoveField(
            model_name='loanevaluation',
            name='ai_recommendations',
        ),
        migrations.AlterField(
            model_name='loanevaluation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
