# Generated by Django 4.2.23 on 2025-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(choices=[('car', 'Car Loan'), ('real_estate', 'Real Estate Loan')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('exclusive_interest_rate', models.CharField(max_length=80)),
                ('estimated_term', models.CharField(max_length=80)),
                ('key_requirement', models.CharField(max_length=255)),
                ('key_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('average_processing_time', models.CharField(max_length=80)),
            ],
        ),
    ]
